# Generated by Django 3.2.8 on 2022-06-16 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Seller',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('date_of_birth', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nid_no', models.IntegerField(blank=True, null=True)),
                ('nid_pic_front', models.ImageField(blank=True, null=True, upload_to='media/nid_front/')),
                ('nid_pic_back', models.ImageField(blank=True, null=True, upload_to='media/nid_back/')),
                ('bank_ac_no', models.IntegerField(blank=True, null=True)),
                ('scan_check_leaf', models.ImageField(blank=True, null=True, upload_to='media/check_leaf/')),
                ('Business_name', models.CharField(blank=True, max_length=250, null=True)),
                ('scan_business_license', models.ImageField(blank=True, null=True, upload_to='media/business_license/')),
                ('pick_up_address', models.CharField(blank=True, max_length=250, null=True)),
                ('mobile', models.CharField(blank=True, max_length=250, null=True)),
                ('delivery_type', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('central', 'Central'), ('local', 'Local')], max_length=13, null=True)),
                ('seller', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to='seller.seller')),
            ],
        ),
    ]
